# Generated by Django 5.2.8 on 2025-11-10 17:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя устройства')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('temperature1', models.FloatField(blank=True, null=True, verbose_name='Температура 1')),
                ('temperature2', models.FloatField(blank=True, null=True, verbose_name='Температура 2')),
                ('status', models.IntegerField(choices=[(0, 'Отключено (нет питания)'), (1, 'ОК'), (2, 'Перегрев датчик 1'), (3, 'Перегрев датчик 2'), (4, 'Включено (питание подано)')], default=0, verbose_name='Статус')),
                ('update_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время обновления')),
            ],
            options={
                'verbose_name': 'Статус устройства',
                'verbose_name_plural': 'Статусы устройств',
                'ordering': ['-update_datetime'],
                'indexes': [models.Index(fields=['name'], name='ThermalMap__name_99b5ac_idx'), models.Index(fields=['status'], name='ThermalMap__status_753472_idx'), models.Index(fields=['update_datetime'], name='ThermalMap__update__c8db86_idx')],
            },
        ),
    ]
