# Generated by Django 5.2.8 on 2025-11-10 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThermalMap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestatus',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Широта в градусах от -90 до 90', null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='devicestatus',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Долгота в градусах от -180 до 180', null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Долгота'),
        ),
    ]
