# Generated by Django 5.2.8 on 2025-11-11 11:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThermalMap', '0002_devicestatus_latitude_devicestatus_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestatus',
            name='request_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время запроса'),
        ),
    ]
